"""empty message

Revision ID: c0218ee8ca1e
Revises: 181eb92becc0
Create Date: 2024-11-27 11:21:53.192426

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0218ee8ca1e'
down_revision = '181eb92becc0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('certificate', schema=None) as batch_op:
        batch_op.drop_index('common_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('certificate', schema=None) as batch_op:
        batch_op.create_index('common_name', ['common_name'], unique=True)

    # ### end Alembic commands ###
