"""empty message

Revision ID: 3b32a99ec7bd
Revises: 47ce0a102bcb
Create Date: 2024-11-28 14:06:17.477876

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3b32a99ec7bd'
down_revision = '47ce0a102bcb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transfer_record')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transfer_record',
    sa.Column('create_time', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('status', mysql.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('sender_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('recipient_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('amount', mysql.FLOAT(), nullable=True),
    sa.Column('transfer_type', mysql.VARCHAR(collation='utf8mb4_0900_as_cs', length=20), nullable=True),
    sa.ForeignKeyConstraint(['recipient_id'], ['bank_user.UserId'], name='transfer_record_ibfk_2'),
    sa.ForeignKeyConstraint(['sender_id'], ['bank_user.UserId'], name='transfer_record_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_as_cs',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
