"""empty message

Revision ID: 47ce0a102bcb
Revises: 50f46098364f
Create Date: 2024-11-27 22:04:07.814389

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47ce0a102bcb'
down_revision = '50f46098364f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('oauth_client', schema=None) as batch_op:
        batch_op.add_column(sa.Column('client_name', sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('oauth_client', schema=None) as batch_op:
        batch_op.drop_column('client_name')

    # ### end Alembic commands ###
