"""empty message

Revision ID: 50f46098364f
Revises: 
Create Date: 2024-11-27 21:30:41.726432

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '50f46098364f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shop_user', schema=None) as batch_op:
        batch_op.drop_index('email')

    op.drop_table('shop_user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shop_user',
    sa.Column('create_time', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('status', mysql.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('UserId', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nickname', mysql.VARCHAR(collation='utf8mb4_0900_as_cs', length=24), nullable=False),
    sa.Column('email', mysql.VARCHAR(collation='utf8mb4_0900_as_cs', length=50), nullable=False),
    sa.Column('password', mysql.VARCHAR(collation='utf8mb4_0900_as_cs', length=255), nullable=False),
    sa.Column('isAdmin', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('captcha', mysql.VARCHAR(collation='utf8mb4_0900_as_cs', length=255), nullable=True),
    sa.Column('bank_user_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('captcha_expiry', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('UserId'),
    mysql_collate='utf8mb4_0900_as_cs',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('shop_user', schema=None) as batch_op:
        batch_op.create_index('email', ['email'], unique=True)

    # ### end Alembic commands ###
