"""修改了验证码的逻辑，将验证码存成hash

Revision ID: 2e8983d206c1
Revises: 
Create Date: 2024-10-20 09:13:05.437732

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2e8983d206c1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bank_card', schema=None) as batch_op:
        batch_op.alter_column('captcha',
               existing_type=mysql.VARCHAR(length=6),
               type_=sa.String(length=255),
               existing_nullable=True)

    with op.batch_alter_table('bank_user', schema=None) as batch_op:
        batch_op.alter_column('captcha',
               existing_type=mysql.VARCHAR(length=6),
               type_=sa.String(length=255),
               existing_nullable=True)

    with op.batch_alter_table('shop_user', schema=None) as batch_op:
        batch_op.alter_column('captcha',
               existing_type=mysql.VARCHAR(length=6),
               type_=sa.String(length=255),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shop_user', schema=None) as batch_op:
        batch_op.alter_column('captcha',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=6),
               existing_nullable=True)

    with op.batch_alter_table('bank_user', schema=None) as batch_op:
        batch_op.alter_column('captcha',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=6),
               existing_nullable=True)

    with op.batch_alter_table('bank_card', schema=None) as batch_op:
        batch_op.alter_column('captcha',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=6),
               existing_nullable=True)

    # ### end Alembic commands ###
